services:
  - type: web
    name: indian-railways-ai-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /api/v1/server/telemetry
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: raksha-persistent-storage
      mountPath: /app/data
      sizeGB: 10
