"""
advanced_features_api.py
─────────────────────────────────────────────────────────────────────────────
REST API endpoints for RAKSHA PATH Standout Features:
  - Dynamic Speed Restriction (PSR/TSR) Trade-off Simulator
  - Goods Train Opportunistic Windowing
  - Heavy Machinery & Resource Load Balancer
  - Post-Block Yield & Burst Scorecard
  - Emergency Rail Fracture / OHE Snap Rerouting Assistant
  - Time-Distance String Diagram (Marey Chart)
  - Multi-Horizon Tactical & Strategic Planner
─────────────────────────────────────────────────────────────────────────────
"""

import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, HTTPException, Query, Path as FPath
from pydantic import BaseModel, Field

MODULE_DIR = Path(__file__).resolve().parent
AI_MODELS_DIR = MODULE_DIR.parent
if str(AI_MODELS_DIR) not in sys.path:
    sys.path.insert(0, str(AI_MODELS_DIR))

from shared.logger import get_logger

# Import from block-optimizer using importlib or direct import
try:
    from block_optimizer.advanced_features import (
        TSRTradeoffSimulator,
        OpportunisticWindowDetector,
        ResourceFleetBalancer,
        PostBlockScorecard,
        EmergencyReroutingAssistant,
        StringDiagramGenerator,
        MultiHorizonPlanner,
    )
except ImportError:
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "adv_feat", str(AI_MODELS_DIR / "block-optimizer" / "advanced_features.py")
    )
    adv_feat = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(adv_feat)
    TSRTradeoffSimulator = adv_feat.TSRTradeoffSimulator
    OpportunisticWindowDetector = adv_feat.OpportunisticWindowDetector
    ResourceFleetBalancer = adv_feat.ResourceFleetBalancer
    PostBlockScorecard = adv_feat.PostBlockScorecard
    EmergencyReroutingAssistant = adv_feat.EmergencyReroutingAssistant
    StringDiagramGenerator = adv_feat.StringDiagramGenerator
    MultiHorizonPlanner = adv_feat.MultiHorizonPlanner

logger = get_logger("advanced_features_api")
router = APIRouter(prefix="/api/v1/advanced", tags=["Standout Railway AI Features"])


class TSRSimulationRequest(BaseModel):
    defect_type: str = Field(default="Ultrasonic Flaw (IMR)")
    corridor_speed_kmh: float = Field(default=130.0, ge=60, le=160)
    tsr_speed_kmh: float = Field(default=30.0, ge=10, le=75)
    restriction_length_km: float = Field(default=2.5, ge=0.5, le=20.0)
    daily_train_density: int = Field(default=48, ge=10, le=120)
    deferral_days: int = Field(default=7, ge=1, le=30)
    block_duration_minutes: int = Field(default=120, ge=30, le=360)
    trains_regulated_during_block: int = Field(default=4, ge=0, le=20)


class ValidateResourceRequest(BaseModel):
    machine_id: str = Field(default="BCM-372")
    target_km: float = Field(default=142.8)
    scheduled_start_hour: float = Field(default=2.0)


class EmergencyRerouteRequest(BaseModel):
    section_id: str = Field(default="NDLS-CNB-UP")
    incident_type: str = Field(default="Rail Fracture (Severe Ultrasonic Break)")
    incident_km: float = Field(default=142.8)
    estimated_restoration_minutes: int = Field(default=180, ge=30, le=720)


@router.post("/tsr-tradeoff", summary="Dynamic Speed Restriction (PSR/TSR) Trade-off Simulator")
def simulate_tsr_tradeoff(req: TSRSimulationRequest) -> Dict[str, Any]:
    """Calculates train punctuality minutes lost if defect deteriorates to a TSR vs immediate block."""
    try:
        return TSRTradeoffSimulator.calculate_tradeoff(
            defect_type=req.defect_type,
            corridor_speed_kmh=req.corridor_speed_kmh,
            tsr_speed_kmh=req.tsr_speed_kmh,
            restriction_length_km=req.restriction_length_km,
            daily_train_density=req.daily_train_density,
            deferral_days=req.deferral_days,
            block_duration_minutes=req.block_duration_minutes,
            trains_regulated_during_block=req.trains_regulated_during_block,
        )
    except Exception as e:
        logger.error(f"Error in TSR tradeoff calculation: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/opportunistic-windows/{section_id}", summary="Goods Train Forecast Opportunistic Windows")
def get_opportunistic_windows(section_id: str = FPath(..., description="Section Code (e.g. NDLS-CNB-UP)")) -> List[Dict[str, Any]]:
    """Identifies micro-possession windows generated by unexpected freight turnaround and loading buffers."""
    try:
        return OpportunisticWindowDetector.find_opportunistic_windows(section_id=section_id)
    except Exception as e:
        logger.error(f"Error detecting opportunistic windows: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/resource-fleet", summary="Heavy Track Machine & Crew Fleet Status")
def get_resource_fleet() -> List[Dict[str, Any]]:
    """Lists divisional BCMs, Tampers, DGS, and TRD Tower Wagons with stabling depots and crew availability."""
    try:
        return ResourceFleetBalancer.get_fleet_status()
    except Exception as e:
        logger.error(f"Error fetching resource fleet: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/validate-resources", summary="Validate Heavy Track Machine Transit & Prevent Ghost Blocks")
def validate_resources_for_block(req: ValidateResourceRequest) -> Dict[str, Any]:
    """Checks transit speed and distance constraints to verify that machinery can reach the block site."""
    try:
        return ResourceFleetBalancer.validate_resource_for_block(
            machine_id=req.machine_id,
            target_km=req.target_km,
            scheduled_start_hour=req.scheduled_start_hour,
        )
    except Exception as e:
        logger.error(f"Error validating resource: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/yield-scorecard", summary="Automated Post-Block Yield & Burst Scorecard")
def get_post_block_scorecard() -> Dict[str, Any]:
    """Returns quarterly departmental yield percentages, burst penalties, and DRR priority modifiers."""
    try:
        return PostBlockScorecard.get_scorecard()
    except Exception as e:
        logger.error(f"Error fetching yield scorecard: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/emergency-reroute", summary="Emergency Rail Break / OHE Snap Rerouting Assistant")
def calculate_emergency_reroute(req: EmergencyRerouteRequest) -> Dict[str, Any]:
    """Calculates instantaneous passenger regulation and EDFC freight bypass for sudden track snaps."""
    try:
        return EmergencyReroutingAssistant.calculate_emergency_reroute(
            section_id=req.section_id,
            incident_type=req.incident_type,
            incident_km=req.incident_km,
            estimated_restoration_minutes=req.estimated_restoration_minutes,
        )
    except Exception as e:
        logger.error(f"Error calculating emergency reroute: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/string-diagram-data/{section_id}", summary="Digital Twin String Diagram (Marey Chart) Data")
def get_string_diagram_data(section_id: str = FPath(..., description="Section Code (e.g. NDLS-CNB-UP)")) -> Dict[str, Any]:
    """Supplies time-distance trajectories and defect hotspots for the interactive canvas."""
    try:
        return StringDiagramGenerator.get_string_diagram_data(section_id=section_id)
    except Exception as e:
        logger.error(f"Error generating string diagram data: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/multi-horizon-plan", summary="Multi-Horizon Planner (Weekly Tactical & Monthly Strategic)")
def get_multi_horizon_plan() -> Dict[str, Any]:
    """Generates weekly tactical possessions and monthly heavy track machine overhaul campaigns."""
    try:
        return MultiHorizonPlanner.get_multi_horizon_plans()
    except Exception as e:
        logger.error(f"Error generating multi-horizon plan: {e}")
        raise HTTPException(status_code=500, detail=str(e))
